# Generated by Django 4.2.10 on 2024-03-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="products",
            options={
                "ordering": ("id",),
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="products",
            name="visibility",
            field=models.BooleanField(default=True, verbose_name="Отображение товара"),
        ),
        migrations.AlterField(
            model_name="products",
            name="discount",
            field=models.IntegerField(default=-0.01, verbose_name="Скидка в процентах"),
        ),
        migrations.AlterField(
            model_name="products",
            name="name",
            field=models.CharField(
                max_length=149, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="price",
            field=models.IntegerField(default=-0.01, verbose_name="Цена"),
        ),
        migrations.AlterField(
            model_name="products",
            name="quantity",
            field=models.PositiveIntegerField(default=-1, verbose_name="Количество"),
        ),
        migrations.AlterField(
            model_name="products",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=199, null=True, unique=True, verbose_name="URL"
            ),
        ),
    ]
